### ISSUE TITLE
Improve Token Security

### ISSUE THREAD

**Issue by type1fool** [liveshowy/webauthn_components#42]
At the Denver Elixir meetup, one of the attendees (@RGENT) raised a concern about token security ([video link](https://youtu.be/lX7NGm2XNV8?t=3421)).

In short, the token saved in sessionStorage may be accessed by 3rd party JS dependencies. Suggested mitigations include cookie storage and/or adding content security policy (CSP).

Because these component interact exclusively via WebSockets, cookies may not be an option here. CSP is likely the better solution, though other alternatives may exist.

## Resources

- [Google Search "sessionstorage security"](https://www.google.com/search?client=safari&rls=en&q=sessionstorage+security&ie=UTF-8&oe=UTF-8)
- Okta Blog: [Secure Browser Storage: The Facts](https://auth0.com/blog/secure-browser-storage-the-facts/)
  - See section on Web Workers
- [CredentialsContainer.store()](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/store) (MDN) 🤩
- [CredentialsContainer.preventSilentAccess()](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/preventSilentAccess) (MDN)

**Comment by RGENT** [comment]
Upon reflection, I think that a CSP is a poor solution to this issue.  They are part of a defense-in-depth solution and aren't intended to act as a primary security mechanism.  They are difficult to set up correctly and often omitted.

**Comment by type1fool** [comment]
@RGENT Interesting. I read through the [Okta blog article](https://auth0.com/blog/secure-browser-storage-the-facts/) about browser storage methods, and it seems like Web Workers would be the solution for this LiveView implementation. Have you dealt with Web Workers for this type of problem?

**Comment by type1fool** [comment]
From #47:

> Instead of setting the token in JS SessionStorage, add a session controller which saves the token in a cookie.
>
> This may eliminate the need for connected?(socket) checks.
>
> Update the demo app to test & document usage.
