### ISSUE TITLE
[REQUEST] - Passkeys input autofill (Conditional UI)

### ISSUE THREAD

**Issue by danielgpinheiro** [liveshowy/webauthn_components#57]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when I need to input again and again my email when I need sign-in. Enabling Passkey Autofill with `mediation: "conditional"` and `autocomplete="username webauthn"` on email input, helps that.

## Describe the solution you'd like

Implements Conditional UI to enable Passkey autofill

## Additional context

[Sign in with a passkey through form autofill](https://web.dev/articles/passkey-form-autofill)
[Add passkeys to the browser autofill](https://developers.google.com/codelabs/passkey-form-autofill#5)
[Explainer: WebAuthn Conditional UI](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI)

## Notify

- @type1fool

**Comment by type1fool** [comment]
@danielgpinheiro Thank you for opening this issue. I will review the links you provided and follow up.

One thing to consider is that the email is only required by the `RegistrationComponent`, and the `AuthenticationComponent` will allow the user to select any passkey registered to the domain. Is this mediation/autofill enhancement related to registering a new account or authenticating an existing one?

**Comment by type1fool** [comment]
It looks like the conditional UI will be helpful for applications migrating from basic auth to Passkeys. I see the value in supporting this user experience, and I do agree that this feature should be on the roadmap.

`WebauthnComponents` is currently focussed on supporting Passkeys in applications with no prior authentication mechanism. The generators in particular assume no prior auth code is in the Phoenix app where they're being run. Integrating WebauthnComponents into apps with basic authentication is a goal of mine, though I expect it to be quite complex. 

This issue has been added to the [WebauthnComponents v1](https://github.com/orgs/liveshowy/projects/3) project, and I will revisit conditional UI once I'm making progress with the basic auth integration.

Thank you. 💟

**Comment by danielgpinheiro** [comment]
Hi, I created a PR to this feature: https://github.com/liveshowy/webauthn_components/pull/59
