### ISSUE TITLE
[REQUEST] - Separate LiveViews for "register" and "login", just like `phx.gen.auth`

### ISSUE THREAD

**Issue by peaceful-james** [liveshowy/webauthn_components#76]
The title says it all. I think the AuthenticationLive module should be split up.

The main reason is for ease of modification, then, I guess "separation of concerns".

I started implementing a 3rd flow for users to create a passkey for an existing account using email confirmation link, and quickly saw I would be using the `RegistrationComponent` for something that is not registration. That was problematic because the event-passing does not refer to the component ID or some other unique identifier. If they were in separate LiveViews, this would not be a problem.

On that note, I would also suggest renaming this to something more explicit like `PasskeyCreationComponent`, since it does not actually know or care about users being registered, only passkeys being created.

Any thoughts are welcome, I am recording "milestone" decisions that will be reflected in my future PR that will have split LIveViews, no user ID in the session and (hopefully) a "lost device" flow.

**Comment by type1fool** [comment]
I've been feeling this itch as well. The single LiveView approach is fine, but not really reflective of how devs typically implement authentication. So, separate LVs seems like a good improvement.

Renaming to something more Passkey-specific may also be a good idea. To my mind, you're "registering" a Passkey whether you're setting up a new account or "registering" an additional Passkey. I do see how that may be misleading or confusing, though.

The package is still pre-1.0, so some renaming and organization improvements should be tackled sooner than later.

What do you think of dropping `Component` from the module names, a la `WebauthnComponents.PasskeyCreation` & `WebauthnComponents.Authentication`, etc.?

**Comment by peaceful-james** [comment]
@type1fool Glad you agree on splitting into separate views. Glad too you agree the meaning of "registration" is overloaded.

I think dropping trailing `Component` from the names is a fine idea.

I hear you about sooner rather than later. When the UVPA PR gets merged, my next PR will be more substantial, with all the stuff I mentioned here and in other issues.

**Comment by type1fool** [comment]
I will take a pass at this today. 

**Todos**

- [ ] Separate reg and auth
- [ ] Refactor Elixir and JS code as needed
- [ ] Update demo repo
